name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # run workflow on push to main branch

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # 3. Install dependencies
    - name: Install dependencies
      run: npm install

    # 4. Run tests
    - name: Run tests
      run: npm test

    # 5. Build Docker image
    - name: Build Docker image
      run: docker build -t myapp:latest .

    # 6. Deploy to Server (via SSH)
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker stop myapp || true
          docker rm myapp || true
          docker run -d -p 80:3000 --name myapp myapp:latest
