jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "hostname"
