name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Update system and install dependencies
          sudo apt update -y
          sudo apt install -y docker.io git

          # Navigate to home directory
          cd ~

          # Clone or update repository
          if [ ! -d "myapp" ]; then
            git clone https://github.com/nidheeshnle/myapp.git
          else
            cd myapp
            git reset --hard
            git pull origin main
            cd ..
          fi

          # Move into repo
          cd myapp

          # Build and run Docker container
          docker stop node-app || true
          docker rm node-app || true
          docker build -t node-app .
          docker run -d -p 80:3000 --name node-app node-app
